# Generated by Django 4.2.2 on 2023-07-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composer',
            name='bio',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='composer',
            name='image',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='composer',
            name='verified_artist',
            field=models.BooleanField(default=False),
        ),
    ]
