# Generated by Django 4.2.2 on 2023-07-02 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_composer_bio_alter_composer_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('year', models.IntegerField(default=0)),
                ('composer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='main_app.composer')),
            ],
        ),
    ]
