# Generated by Django 4.2.2 on 2023-07-02 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='songs',
            new_name='shows',
        ),
    ]
